version: "3.8"

services:
  backend:
    build: ./bookstore-backend
    container_name: bookstore-backend
    ports:
      - "9000:9000"
    volumes:
      - ./bookstore-backend/uploads:/app/uploads
    restart: always

  frontend:
    build: ./bookstore-frontend
    container_name: bookstore-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always